### ISSUE TITLE
Ensure deprecated methods and commands are removed

### ISSUE THREAD

**Issue by wbnns** [cornelius/rpc-docs-helper#1]
@cornelius 

This is as you mentioned to be done more aggressively and also as discussed in https://github.com/bitcoin-dot-org/bitcoin.org/issues/2277.

**Comment by cornelius** [comment]
This is done. Only commands which are regularly available through the command line client are shown. It might be nice to have a list of deprecated and removed commands somewhere so that it would be possible to look up in which version commands have been removed, but that would be a separate issue we can create when the need arises.

**Comment by wbnns** [comment]
@cornelius Thanks, agreed - yes, would be nice to have a way of referenced deprecated commands.

**Comment by cornelius** [comment]
> @cornelius Thanks, agreed - yes, would be nice to have a way of referenced deprecated commands.

I created an issue to keep the idea around: #6

**Comment by wbnns** [comment]
@cornelius 

> I created an issue to keep the idea around: #6

Ok, I see it. 👍
