### ISSUE TITLE
Port documentation to Read the Docs

### ISSUE THREAD

**Issue by wbnns** [cornelius/rpc-docs-helper#5]
@cornelius 

What do you think about initiating an effort to port the documentation to [Read the Docs](https://readthedocs.org/)?

Example:
https://readthedocs.org/projects/solidity/

It would give us some great benefits in terms of versioning, in addition to be in a very recognizable, clear, and easy to read format for developers:
https://solidity.readthedocs.io/en/latest/

I set up a GitHub repository and invited you in case you're interested:
https://github.com/bitcoin-documentation/core

I'd also need your Read the Docs username so I can add you as a maintainer.

Please let me know if you'd like to collaborate together on this.

**Comment by cornelius** [comment]
> What do you think about initiating an effort to port the documentation to Read the Docs?

That makes a lot of sense. And it comes very timely because I just put together a little experiment to convert the developer docs to RST. It can be seen at https://cornelius.github.io/bitcoin-dev-docs/. The sources are at https://github.com/cornelius/bitcoin-dev-docs. It's mostly an automatic conversion. The script to do that is in the [helpers](https://github.com/cornelius/bitcoin-dev-docs/tree/master/helpers) directory.

> Please let me know if you'd like to collaborate together on this.

Absolutely.

**Comment by cornelius** [comment]
This is underway now and living in https://github.com/bitcoin-documentation/bitcoin-dev-docs. I'll close this issue here. We are tracking more detailed issues in the bitcoin-dev-docs repo.
